"""Add hashed_password column to users

Revision ID: 7249a1804bed
Revises: 53a0aecb1a30
Create Date: 2023-07-02 11:23:32.709825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7249a1804bed'
down_revision = '53a0aecb1a30'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hashed_password', sa.String(), nullable=True))
    op.drop_column('users', 'password')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.VARCHAR(), nullable=True))
    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###
